name: Ontracker Tracking Mobile GH Actions

on:
  push:
    branches: 
      - '*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.10'
        channel: 'stable'
    - run: flutter pub get
    - run: flutter test
    - run: flutter analyze

